services:
  dac:
    image: postgres:16
    container_name: Checkin-Checkout
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: check
    ports:
    - "5433:5432"